# Generated by Django 5.2.13 on 2026-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gym_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
