# Generated by Django 5.2.13 on 2026-04-21 06:56

import common.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('gym_owner', 'Gym Owner'), ('staff', 'Staff'), ('lead', 'Lead'), ('member', 'Member'), ('normal_user', 'Normal User')], default=common.constants.enums.UserType['NORMAL_USER'], max_length=20),
        ),
    ]
