# Generated by Django 5.2.13 on 2026-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('standard', 'Standard'), ('elite', 'Elite'), ('premium_plus', 'Premium Plus')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='code',
            field=models.CharField(choices=[('members', 'Members Management'), ('staff', 'Staff Management'), ('dashboard', 'Dashboard'), ('leads', 'Leads / Visitors'), ('expenses', 'Expenses'), ('trainers', 'Trainers'), ('whatsapp', 'WhatsApp Notifications')], max_length=100, unique=True),
        ),
    ]
