# Generated by Django 5.2.13 on 2026-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_plan_name_alter_planfeature_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='badge_color',
            field=models.CharField(default='#4CAF50', max_length=20),
        ),
    ]
