# Generated by Django 5.2.13 on 2026-04-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0008_remove_gym_active_subscription'),
        ('subscriptions', '0003_plan_badge_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='gym_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gyms.gym'),
        ),
    ]
