# Generated by Django 5.2.13 on 2026-05-05 12:06

import common.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_access_type_and_nullable_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='access_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('trial', 'Trial')], default=common.constants.enums.SubscriptionAccessType['PAID'], max_length=20),
        ),
    ]
