# Generated by Django 5.2.13 on 2026-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planfeature',
            name='code',
            field=models.CharField(choices=[('members', 'Members Management'), ('staff', 'Staff Management'), ('dashboard', 'Dashboard'), ('leads', 'Leads / Visitors'), ('expenses', 'Expenses'), ('trainers', 'Trainers'), ('whatsapp', 'WhatsApp Notifications'), ('white_label', 'White Labeling')], max_length=100, unique=True),
        ),
    ]
