# Generated by Django 5.2.13 on 2026-05-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Rent', 'Rent'), ('Maintenance', 'Maintenance'), ('Subscription', 'Subscription'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
