# Generated by Django 5.2.13 on 2026-04-22 14:01

import common.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_payment_status_and_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('DUE', 'Due'), ('OVERDUE', 'Overdue')], default=common.constants.enums.PaymentStatus['DUE'], max_length=20),
        ),
    ]
