# Generated by Django 5.2.13 on 2026-04-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_payment_status_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersubscription',
            name='estimated_remaining_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
