# Generated by Django 5.2.13 on 2026-04-27 08:59

import common.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_membersubscription_estimated_remaining_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default=common.constants.enums.SubscriptionStatus['ACTIVE'], max_length=20),
        ),
    ]
