# Generated by Django 5.2.13 on 2026-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_membersubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'Upi')], max_length=20),
        ),
    ]
