# Generated by Django 5.2.13 on 2026-05-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_memberimportjob_memberimportrowerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpayment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member'),
        ),
    ]
