# Generated by Django 5.2.13 on 2026-05-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_memberpayment_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpayment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AlterField(
            model_name='membersubscription',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
