# Generated by Django 5.2.13 on 2026-04-23 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staff.staff')),
                ('trainer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('max_clients', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('staff.staff',),
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('training_type_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gym_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
