# Generated by Django 5.2.13 on 2026-04-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='state',
        ),
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address'),
        ),
    ]
