# Generated by Django 5.2.13 on 2026-04-11 18:41

import common.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_remove_gym_city_remove_gym_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='onboarding_step',
            field=models.CharField(choices=[('basic', 'Basic'), ('address', 'Address'), ('subscription', 'Subscription'), ('completed', 'Completed')], default=common.constants.enums.OnboardingStep['BASIC'], max_length=20),
        ),
    ]
