# Generated by Django 5.2.13 on 2026-04-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('gyms', '0003_gym_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.address'),
        ),
    ]
