# Generated by Django 5.2.13 on 2026-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_gym_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
