# Generated by Django 5.2.13 on 2026-04-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0005_alter_gym_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='owner_id',
        ),
    ]
