# Generated by Django 5.2.13 on 2026-04-26 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_remove_gym_owner_id'),
        ('subscriptions', '0003_plan_badge_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='active_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
    ]
