# Generated by Django 5.2.13 on 2026-04-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gym_active_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='active_subscription',
        ),
    ]
