# Generated by Django 5.2.13 on 2026-05-05 14:45

import common.constants.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_gymbranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymbranding',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymbranding',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymbranding',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default=common.constants.enums.ThemeMode['DARK'], max_length=20),
        ),
    ]
